ansible_user: ec2-user
ansible_password: DevOps321

#databases
mongodb_host: mongodb-{{ env }}.devopswiththota.online
redis_host: redis-{{ env }}.devopswiththota.online
mysql_host: mysql-{{ env }}.devopswiththota.online
rabbitmq_host: rabbitmq-{{ env }}.devopswiththota.online

#components
catalogue_host: catalogue.backend-alb-{{ env }}.devopswiththota.online
cart_host: cart.backend-alb-{{ env }}.devopswiththota.online
user_host: user.backend-alb-{{ env }}.devopswiththota.online
shipping_host: shipping.backend-alb-{{ env }}.devopswiththota.online
payment_host: payment.backend-alb-{{ env }}.devopswiththota.online
